ImwebIS01/ImMall

server/.prettierrc

prettier 셋팅 
[ ] Warning Message가 발생하지 않았나요?
[ ] Coding Convention을 준수했나요?
[ ] Test Code를 작성하였나요?
prettier 옵션 추가 
❌
0.5h

[Pi01-116]style: eslint prettier 세팅

---

.vscode/extensions.json
server/package-lock.json
server/package.json
server/src/database/database.module.ts
server/src/database/database.service.ts
server/src/database/test.sql
server/src/user/dto/auth-credential.dto.ts
server/src/user/dto/create-user.dto.ts
server/src/user/entities/user.entity.ts
server/src/user/strategies/jwt.strategy.ts
server/src/user/user.controller.ts
server/src/user/user.module.ts
server/src/user/user.repository.ts
server/src/user/user.service.ts

📑 개요
(작업 내역 한줄로 요약)
(작업 내역 확인하기 편하도록 gif 첨부, 필수 아님 사진으로 대체 가능)
✔️ 셀프 체크리스트
[✔️ ] Warning Message가 발생하지 않았나요?
[✔️ ] Coding Convention을 준수했나요?
[ ]Test Code를 작성하였나요?
💬 작업 내용
DB Connection, Transaction 관련 메서드 모듈화
USER API 잔버그 수정
🚧 PR 특이 사항
특이사항은 없고 Pull 받고 작업하시면 더 편할 것입니다! 
🕰 소요 시간
1h

Pi01 148 db 커넥션 메서드 설계

---

server/src/user/entities/user.entity.ts

📑 개요
(작업 내역 한줄로 요약)
(작업 내역 확인하기 편하도록 gif 첨부, 필수 아님 사진으로 대체 가능)
✔️ 셀프 체크리스트
[✔️] Warning Message가 발생하지 않았나요?
[✔️] Coding Convention을 준수했나요?
[✔️]Test Code를 작성하였나요?
💬 작업 내용
유저 스키마 초안 작성(Confluence 블로그 Reference 참고)
🚧 PR 특이 사항
createdAt, updatedAt 통일, 
🕰 소요 시간
0.2h

Pi01 125 유저 스키마 초안

---

server/src/database/database.service.ts
server/src/user/dto/create-user.dto.ts

📑 개요
범용적으로 활용하고자 Database Service class에 uuid 활용한 genCode 메서드 생성
✔️ 셀프 체크리스트
[ ] Warning Message가 발생하지 않았나요?
[ ] Coding Convention을 준수했나요?
[ ]Test Code를 작성하였나요?
💬 작업 내용
범용적으로 활용하고자 Database Service class에 uuid 활용한 genCode 메서드 생성
🚧 PR 특이 사항
🕰 소요 시간
0.2h

Pi01 126 유저 레포지토리: genCode

---

server/package-lock.json
server/package.json
server/src/user/dto/create-user.dto.ts
server/src/user/entities/user.entity.ts
server/src/user/user.controller.ts
server/src/user/user.repository.ts
server/src/user/user.service.ts

📑 개요
유저 레포지토리 구현
✔️ 셀프 체크리스트
[✔️] Warning Message가 발생하지 않았나요?
✔️] Coding Convention을 준수했나요?
[ ]Test Code를 작성하였나요?
💬 작업 내용
- 유저 레포지토리 개발
- 유저 스키마 수정
🚧 PR 특이 사항
단순 read 작업은 단일 query, write 작업은 트렌젝션 처리
🕰 소요 시간
1.5h

feat: 유저 레포지토리 개발

---

server/src/app.module.ts
server/src/order/dto/create-order.dto.ts
server/src/order/dto/update-order.dto.ts
server/src/order/entities/order.entity.ts
server/src/order/order.controller.spec.ts
server/src/order/order.controller.ts
server/src/order/order.module.ts
server/src/order/order.repository.ts
server/src/order/order.service.spec.ts
server/src/order/order.service.ts

주문 API 기본 CRUD와 세팅
기초적인 부분들만 작업 해놓았으므로 좀 더 통합적인 수정이 필요
❌
4h

Pi01 129 주문 스키마 초안

---

server/src/app.controller.spec.ts
server/src/database/database.service.ts
server/src/user/user.repository.spec.ts
server/src/user/user.repository.ts

DB 커넥션 풀 생성 및 관련 메서드 구현
- [✔️] Warning Message가 발생하지 않았나요?
- ✔️] Coding Convention을 준수했나요?
- 커넥션 풀 생성: connectionLimit: 10, connectTimeout: 5000
- Database Service 메서드 수정(기존 connection 생성 후 사용하던 메서드들을 모두 Pool을 사용하도록 구현)
- 커넥션과 커넥션 풀에 대한 공부를 좀 더 해서 효율적인 커넥션 매커니즘을 구성해볼 필요가 있음
3h

Pi01 156 db pooling 구현

---

server/src/order/order.repository.ts

db method 수정사항 반영
- [✔️] Warning Message가 발생하지 않았나요?
- [✔️] Coding Convention을 준수했나요?
db method 수정사항 반영
10s

Hotfix db method 수정

---

server/src/main.ts
server/src/user/user.controller.ts
server/src/user/user.repository.ts
server/src/user/user.service.ts

유저 컨트롤러 페이지네이션 작성
(작업 내역 확인하기 편하도록 gif 첨부, 필수 아님 사진으로 대체 가능)
- [✔️] Warning Message가 발생하지 않았나요?
- [✔️] Coding Convention을 준수했나요?
유저 컨트롤러 페이지네이션 작성
DTO 및 반환타입 수정중
0.5h

feat: 유저 컨트롤러(페이지네이션) 개발

---

server/package-lock.json
server/package.json
server/src/app.module.ts
server/src/user/dto/get-user.dto.ts
server/src/user/user.controller.spec.ts
server/src/user/user.controller.ts
server/src/user/user.service.ts

유저 서비스 로직, DTO 수정
유저 서비스 로직, DTO 수정
2h

Pi01 127 유저 서비스

---

server/src/app.module.ts
server/src/membership/dto/create-membership.dto.ts
server/src/membership/dto/get-membership.dto.ts
server/src/membership/dto/update-membership.dto.ts
server/src/membership/entities/membership.entity.ts
server/src/membership/membership.controller.spec.ts
server/src/membership/membership.controller.ts
server/src/membership/membership.module.ts
server/src/membership/membership.service.spec.ts
server/src/membership/membership.service.ts

feat: 멤버쉽 DTO 작성

---

server/src/membership/dto/create-membership.dto.ts
server/src/membership/dto/get-membership.dto.ts
server/src/membership/membership.controller.spec.ts
server/src/membership/membership.controller.ts
server/src/membership/membership.module.ts
server/src/membership/membership.service.spec.ts
server/src/membership/membership.service.ts
server/src/mock-data.ts
server/src/user/user.controller.spec.ts

멤버쉽 서비스, 컨트롤러 CRUD & Unit Test 
- 멤버쉽 서비스, 컨트롤러 CRUD 
- Membership Controller Unit Test
문서를 꼭 정독해주세요!! 
https://imweb.atlassian.net/wiki/spaces/PIS/pages/25592181/Test+Code+1+-+Controller
6h

Pi01 180 멤버쉽 서비스 컨트롤러 crud 작성 + TDD

---

server/src/membership/dto/get-membership.dto.ts
server/src/mock-data.ts
server/src/user/dto/auth-credential.dto.ts
server/src/user/dto/create-user.dto.ts
server/src/user/dto/get-user.dto.ts
server/src/user/dto/save-user.dto.ts
server/src/user/user.controller.ts
server/src/user/user.service.ts

user-site 연결
- site 생성 후 유저 컨트롤러 및 서비스에 site를 연결
- dto 수정
- 기존 idx 조회, 수정, 삭제 등을 직접 생성한 code로 대체(추후 인덱싱 적용 예정)
2h

user-site 연결

---

server/src/database/database.module.ts
server/src/membership/membership.controller.spec.ts
server/src/membership/membership.module.ts

멤버쉽 유닛 테스트 종속성 추가
유닛 테스트에 종속성을 추가한 간단한 작업입니다. 브랜치 분기를 위해 merge합니다. 
ex) 0.1h(시간)

fix: membership 유닛 테스트 종속성 추가

---

server/src/database/database.module.ts

데이터베이스 모듈 Config 종속성 주입
데이터베이스 모듈 Config 종속성 주입
0.1h

fix: 데이터베이스 모듈 Config 종속성 주입

---

server/src/order/dto/get-order.dto.ts
server/src/order/order.controller.ts
server/src/order/order.module.ts
server/src/order/order.service.ts

주문 CRUD 완성 - 오류체크 완료
get-order dto 생성
order service 수정
order.service.ts 83-85줄에서 다시 dto를 검사하는게 있는데 제가 이해한것이 맞다면 코멘트 부탁드립니다. 😄
3h(시간)

feat: 주문 CRUD 완성

---

server/src/app.module.ts
server/src/products/dto/get-product.dto.ts
server/src/products/products.service.ts
server/src/refund/dto/create-refund.dto.ts
server/src/refund/dto/get-refund.dto.ts
server/src/refund/dto/update-refund.dto.ts
server/src/refund/refund.controller.spec.ts
server/src/refund/refund.controller.ts
server/src/refund/refund.module.ts
server/src/refund/refund.service.spec.ts
server/src/refund/refund.service.ts

refund  CRUD
구현 내용 및 작업 했던 내역
Refund DTO
Refund service
Refund controller
nope
1h

Pi01 194 환불 컨트롤러

---

server/src/order/order.service.ts

테이블 이름 수정과 예외처리 개선사항 적용
예약어인 order를 전부 변경
1. testA.order -> orders 
2. 예외처리 개선사항 적용 : https://imweb.atlassian.net/wiki/spaces/PIS/pages/27788260
❌
1h(시간)

hotfix: 테이블 이름 수정과 예외처리 개선사항 적용

---

server/src/order/order.controller.ts
server/src/order/order.service.ts

Transaction 구현 완료
1. order service쪽 transaction 구현 완료
❌
1h(시간)

feat: transaction 틀 완성

---

server/src/app.module.ts
server/src/points/points.controller.spec.ts
server/src/points/points.controller.ts
server/src/points/points.module.ts
server/src/points/points.service.spec.ts
server/src/points/points.service.ts

기본 points 컨트롤 모듈 추가
1. contoller 추가
2. module 추가
3. service 추가
nest cli 통한 기본적인 추가입니다. 
0.5h(시간)

feat: points mo,controller 추가

---

server/src/app.module.ts
server/src/points/dto/create-points.dto.ts
server/src/points/dto/get-points.dto.ts
server/src/points/points.controller.ts
server/src/points/points.module.ts
server/src/points/points.service.ts

1. controller, service, dto 틀 완성
2. 테스트 코드 작성 필요.
1. dto
2. service
3. contoller
❌
2h(시간)

PI01-172-포인트-서비스

---

server/src/app.module.ts
server/src/order/order.module.ts
server/src/order/order.service.ts
server/src/useful/useful.service.ts
server/src/useful/userful.module.ts

포인트 적립 transaction 작업
오더 - 포인트 - 포인트 Applied 테이블로 이어지는 transaction 작업 완료 문제 없이 작동
❌
2h(시간)

PI01-208-포인트-적립-transaction

---

server/src/useful/useful.service.ts

useful 주석추가
useful 주석 추가
❌
0.1h

PI01-210-useful-주석-추가-작업

---

client/package-lock.json
client/package.json
server/src/order/order.controller.spec.ts

오더 테스트 코드 오류 수정 , react 의존성 추가
오더 컨트롤 테스트 코드 수정
+ react package.json axios, styled-component추가
❌
0.1h(시간)

Pi01 213 로그인 화면

---

server/src/database/database.service.ts
server/src/membership/membership.controller.spec.ts
server/src/user/user.service.ts

Hotfix db method 에러핸들링
getConnection을 db service method 단에서 try catch 처리, 다른 서비스 구문에서 if문 분기 에러 처리를 생략해도 될 것 같습니다. 
0.1h

Hotfix db method 에러핸들링

---

client/src/components/ChurnBox.js

feat: article  edit

---

server/src/order/order.service.ts
server/src/points/points.service.ts

error 로직에도 커넥션풀 release가 들어가야합니다.
catch(error)에서도 
con.release 로 커넥션풀 할당해제 
❌
0.2h(시간)

PI01 219 transaction 커넥션풀 release

---

server/package.json
server/src/products/products.service.spec.ts
server/src/products/products.service.ts
server/src/refund/refund.controller.spec.ts
server/src/refund/refund.service.ts

환불 unit test
환불 controller unit test
typescript 에러 수정
nope
2h

환불 controller unit test

---

server/src/main.ts
server/src/util/logging.interceptor.ts
server/src/util/transform.interceptor.ts

글로벌 로깅, 트랜스폼  인터셉터 추가
1. 로깅 추가
2. 트랜스폼 추가
❌
3h(시간)

PI01 224 로깅,트랜스폼 인터셉터

---

server/src/products/products.module.ts
server/src/products/products.service.ts

상품 서비스 추가 수장
상품 정보로 주문정보가져오기 서비스 추가
release 방식 수정
nope
1h

fix: product service edit

---

server/src/refund/refund.controller.spec.ts
server/src/refund/refund.controller.ts
server/src/refund/refund.service.ts

환불 서비스 추가 개발
1. 트랜젝션을 활용해 refunds, refund_order_product 테이블 연결
2. release 방식 수정
3. refund code로 products, orders table 정보 가져오느 서비스 작성
nope
4h

feat: 서비스 추가 개발

---

client/.prettierrc
client/src/apis/ChurnDataApi.js
server/src/main.ts
server/src/message.producer.service.ts
server/src/order/dto/create-order.dto.ts
server/src/order/order.controller.spec.ts
server/src/order/order.controller.ts
server/src/order/order.module.ts
server/src/order/order.service.ts
server/src/util/logging.interceptor.ts

오더 - 프로덕트 수량 변경 트랜지션 수정
(환불 트랜지션을 위해서 로직 변경)
- 로깅 변경
- 오더 - 프로덕트 트랜지션 수정
- 프로덕트 수량에 맞춰서 데이터 삽입 추가
❌
4h(시간)

Pi01 237 환불 트랜지션

---

server/package.json
server/src/mock-data.ts
server/src/refund/refund.service.spec.ts
server/src/refund/refund.service.ts

refund service-unit-test
refund service unittest
nope
5h

PI01-226-환불-unit-test
